ALTER TABLE products
  ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 1;

ALTER TABLE categories
  ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 1;

ALTER TABLE pages
  ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 1;
