FROM node:20-alpine AS build

ARG ETK_WEB_VERSION=development
ARG ETK_GIT_COMMIT=unknown
ARG ETK_BUILD_TIME=unknown
ARG ETK_RELEASE_CHANNEL=development

ENV VITE_APP_VERSION=${ETK_WEB_VERSION}
ENV VITE_GIT_COMMIT=${ETK_GIT_COMMIT}
ENV VITE_BUILD_TIME=${ETK_BUILD_TIME}
ENV VITE_RELEASE_CHANNEL=${ETK_RELEASE_CHANNEL}

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM caddy:2.8-alpine

COPY deploy/Caddyfile.docker /etc/caddy/Caddyfile
COPY --from=build /app/dist /srv
